name-template: "NanoPlaceR $RESOLVED_VERSION Release"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features and Enhancements"
    when:
      labels:
        - "feature"
        - "usability"
  - title: "🐛 Bug Fixes"
    when:
      labels:
        - "bug"
  - title: "📄 Documentation"
    when:
      labels:
        - "documentation"
  - title: "🤖 CI"
    when:
      labels:
        - "continuous integration"
  - title: "📦 Packaging"
    when:
      labels:
        - "packaging"
  - title: "⬆️ Dependencies"
    collapse-after: 5
    when:
      labels:
        - "dependencies"
        - "submodules"
        - "github_actions"
  - type: version-resolver
    semver-increment: major
    when:
      label: "major"
  - type: version-resolver
    semver-increment: minor
    when:
      label: "minor"
  - type: version-resolver
    semver-increment: patch
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

template: |
  ## What Changed 👀

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
